In [1]:
x, y = 1, 2

In [2]:
x, y

(1, 2)

In [3]:
x == y

False

In [4]:
x != y

True

In [5]:
x = ['Hello', 'World']

In [7]:
'Hello' not in x

False

In [8]:
x, y, z = 1, 2, 3

In [9]:
(x == y) and (y == z)

False

In [10]:
(x == y) and (y != z)

False

In [11]:
(x == y) or (y != z)

True

In [13]:
not x == y

True

In [14]:
friends = ['Alice', 'Beth']

In [15]:
if 'Alice' in friends:
  print('Alice is my friend.')

Alice is my friend.


In [19]:
x = 'Bob'
if x in friends:
  print(f'{x} is my friend.')

In [20]:
x = 'Bob'
if x in friends:
  print(f'{x} is my friend.')
  # code....
else:
  print(f'{x} is not my friend.')

Bob is not my friend.


In [21]:
if 'Alice' in friends:
  print('Alice is my friend.')
elif 'Beth' in friends:
  print('Beth is my friend, but Alice is not.')
else:
  print('Both are not my friends.')

Alice is my friend.


In [ ]:
if 'Alice' in friends:
  print('Alice is my friend.')
else:
  print('Alice is not my friend.')

In [23]:
msg = 'Alice is my friend.' if 'Alice' in friends else 'Alice is not my friend.'

Alice is my friend.


In [ ]:
help(range)

In [26]:
list(range(1, 11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [31]:
for x in range(1, 11, 2):
  print(x)

1
3
5
7
9


In [34]:
x = 1
while x <= 10:
  print(x)
  x += 2

1
3
5
7
9


In [42]:
for x in range(1, 11):
  if x % 3 == 0:
    print(x**2)
  else:
    print(x)

1
2
9
4
5
36
7
8
81
10


In [38]:
[x**2 for x in range(1, 11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [44]:
[x**2 for x in range(1, 11) if x % 3 == 0]

[9, 36, 81]

In [46]:
[x**2 if x % 3 == 0 else x for x in range(1, 11)]

[1, 2, 9, 4, 5, 36, 7, 8, 81, 10]

In [47]:
def sum_three_numbers(a, b, c):
  print(a+b+c)

In [48]:
sum_three_numbers(1, 2, 3)

6


In [49]:
x = sum_three_numbers(1, 2, 3)

6


In [51]:
print(x)

None


In [52]:
def sum_three_numbers(a, b, c):
  return a+b+c

In [53]:
y = sum_three_numbers(1, 2, 3)

In [54]:
print(y)

6


In [55]:
def sum_and_product_three_numbers(a, b, c):
  s = a+b+c
  p = a*b*c
  print('The sum is', s, 'and the product is', p)
  return s, p

In [56]:
ss, pp = sum_and_product_three_numbers(2, 3, 4)

The sum is 9 and the product is 24


In [57]:
ss

9

In [58]:
pp

24

In [62]:
ss, pp, tt = sum_and_product_three_numbers(2, 3, 4)

The sum is 9 and the product is 24


ValueError: not enough values to unpack (expected 3, got 2)

In [61]:
type(sspp)

tuple

In [63]:
sspp[0]

9

In [64]:
sspp[1]

24

In [65]:
def sum_three_numbers(a, b, c):
  return a+b+c

In [66]:
sum_three_numbers_lambda = lambda a, b, c: a+b+c

In [67]:
type(sum_three_numbers_lambda)

function

In [68]:
sum_three_numbers_lambda(1, 2, 3)

6

In [69]:
l = [6, 7.5, 8, 0, 1]

In [70]:
len(l)

5

In [71]:
import numpy as np

In [72]:
a = np.array(l)

In [73]:
a

array([6. , 7.5, 8. , 0. , 1. ])

In [74]:
type(a)

numpy.ndarray

In [87]:
l2 = [[1.0, 2, 3, 4],
      [5, 6, 7, 8]]

In [76]:
l2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [88]:
a2 = np.array(l2)

In [78]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
a.shape

(5,)

In [80]:
a2.shape

(2, 4)

In [83]:
len(a.shape)

1

In [81]:
a.ndim

1

In [84]:
len(a2.shape)

2

In [82]:
a2.ndim

2

In [85]:
a.dtype

dtype('float64')

In [89]:
a2.dtype

dtype('float64')

In [90]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

In [91]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
a2.shape

(3, 3)

In [93]:
a2[1, 1]

5

In [94]:
l2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [95]:
l2[1][1]

5

In [96]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
a2[:2, 1:]

array([[2, 3],
       [5, 6]])

In [108]:
a2[2, :]

array([7, 8, 9])

In [105]:
a2[:, 2]

array([3, 6, 9])

In [110]:
a2[2:, :].shape

(1, 3)

In [111]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
a2.mean()

5.0

In [113]:
a2.sum()

45

In [114]:
a2.mean(axis=0)

array([4., 5., 6.])

In [115]:
a2.mean(axis=1)

array([2., 5., 8.])

In [116]:
from numpy.random import normal

In [ ]:
help(normal)

In [122]:
normal(size=(5, 10))

array([[-0.27321092, -0.40542792,  0.4938129 , -0.9343531 ,  1.22623498,
        -1.66255332, -0.89983572,  0.71721633, -1.42262975,  0.17550164],
       [ 0.35542615, -1.40941767,  0.34333747,  0.11243763, -3.44986958,
        -0.44347982,  0.23204179,  1.29012727, -1.34964536,  1.06375602],
       [-0.41895472,  0.89730993, -1.74634604, -0.15754786, -1.08027755,
        -0.47703379,  0.74420745,  1.87535868, -0.85012505,  1.13903391],
       [-1.6870191 , -0.86012782,  2.28707586, -0.34175071, -0.6647799 ,
         0.73161518,  2.35969359, -0.46363652,  0.50073594, -0.22818541],
       [-0.12027896,  0.28357961, -1.74654418, -1.038007  ,  0.29716948,
        -0.35267093,  0.96505314, -0.42366632,  2.34443016,  0.2388964 ]])

In [123]:
from numpy.random import seed

In [135]:
seed(0)
normal(size=(5, 10))

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
         0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462,
        -1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215,
         0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218,
        -0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028]])