In [1]:
x, y = 1, 2

In [2]:
x, y

(1, 2)

In [7]:
x != y

True

In [8]:
x = ['Hello', 'World']

In [12]:
'hello' not in x

True

In [13]:
x, y, z = 1, 2, 3

In [14]:
(x == y) and (y == z)

False

In [15]:
(x == y) and (y != z)

False

In [16]:
(x == y) or (y != z)

True

In [18]:
not (x == y)

True

In [19]:
friends = ['Alice', 'Beth']

In [22]:
x  = 'Bob'
if x in friends:
  print(f'{x} is my friend.')

In [24]:
x  = 'Bob'
if x in friends:
  print(f'{x} is my friend.')
else:
  print(f'{x} is not my friend.')

Bob is not my friend.


In [26]:
if 'Adam' in friends:
  print('Adam is my friend.')
elif 'Bob' in friends:
  print('Bob is my friend.')
else:
  print('Both are not my friends.')

Both are not my friends.


In [27]:
if 'Alice' in friends:
  print('Alice is my friend')
else:
  print('Alice is not my friend')

Alice is my friend


In [28]:
print('Alice is my friend' if 'Alice' in friends else 'Alice is not my friend')

Alice is my friend


In [36]:
x = 1
while x <= 10:
  print(x)
  x += 2

1
3
5
7
9


In [38]:
list(range(1, 11, 2))

[1, 3, 5, 7, 9]

In [ ]:
help(range)

In [46]:
for x in range(1, 11):
  print(x**2)

1
4
9
16
25
36
49
64
81
100


In [49]:
tuple(x**2 for x in range(1, 11, 2))

(1, 9, 25, 49, 81)

In [47]:
for x in range(1, 11):
  if x % 3 == 0:
    print(x**2)

9
36
81


In [50]:
[x**2 for x in range(1, 11) if x % 3 == 0]

[9, 36, 81]

In [51]:
for x in range(1, 11):
  if x % 3 == 0:
    print(x**2)
  else:
    print(x)

1
2
9
4
5
36
7
8
81
10


In [52]:
[x**2 if x % 3 == 0 else x for x in range(1, 11)]

[1, 2, 9, 4, 5, 36, 7, 8, 81, 10]

In [55]:
def sum_three_numbers(a, b, c):
  print('the sum is', a+b+c)

In [57]:
result = sum_three_numbers(1, 2, 3)

the sum is 6


In [59]:
print(result)

None


In [60]:
def sum_three_numbers(a, b, c):
  s = a+b+c
  print('the sum is', s)
  return s

In [61]:
result = sum_three_numbers(1, 2, 3)

the sum is 6


In [62]:
result

6

In [63]:
def sum_and_product_three_numbers(a, b, c):
  s = a+b+c
  p = a*b*c
  print('the sum is', s, 'and the product is', p)
  return s, p

In [66]:
ss, pp = sum_and_product_three_numbers(2, 3, 4)

the sum is 9 and the product is 24


In [72]:
sspp = sum_and_product_three_numbers(2, 3, 4)

the sum is 9 and the product is 24


In [74]:
type(sspp)

tuple

In [67]:
ss

9

In [68]:
pp

24

In [69]:
sum_lambda = lambda a, b, c: a+b+c

In [70]:
type(sum_lambda)

function

In [71]:
sum_lambda(1, 2, 3)

6

In [75]:
l = [6, 7.5, 8, 0, 1]

In [76]:
import numpy as np

In [77]:
a = np.array(l)

In [78]:
a

array([6. , 7.5, 8. , 0. , 1. ])

In [79]:
type(a)

numpy.ndarray

In [80]:
a.dtype

dtype('float64')

In [93]:
l2 = [[1.0, 2, 3, 4],
      [5, 6, 7, 8]]

In [82]:
l2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [94]:
a2 = np.array(l2)

In [84]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
a.shape

(5,)

In [89]:
len(a.shape)

1

In [86]:
a2.shape

(2, 4)

In [90]:
len(a2.shape)

2

In [87]:
a.ndim

1

In [88]:
a2.ndim

2

In [91]:
a.dtype

dtype('float64')

In [95]:
a2.dtype

dtype('float64')

In [98]:
l = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

In [99]:
l[1][1]

5

In [96]:
a2d = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [97]:
a2d.shape

(3, 3)

In [100]:
a2d[1, 1]

5

In [105]:
a2d[0, 2] = 3

In [106]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
a2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [108]:
a2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [115]:
a2d[2, 0:3]

array([7, 8, 9])

In [116]:
a

array([6. , 7.5, 8. , 0. , 1. ])

In [117]:
a.mean()

4.5

In [118]:
a.sum()

22.5

In [119]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
a2d.mean()

5.0

In [121]:
a2d.mean(axis=0)

array([4., 5., 6.])

In [122]:
a2d.mean(axis=1)

array([2., 5., 8.])

In [123]:
from numpy.random import normal

In [ ]:
help(normal)

In [127]:
an = normal(size=(10, 20))

In [128]:
an.mean()

0.1002728936682342

In [129]:
an.std()

1.0060903497442728

In [135]:
normal(size=(3, 5))

array([[ 0.40942091, -1.01103469, -0.51173787,  1.07981692, -0.55025859],
       [-0.1350782 , -0.5005542 ,  0.73264369, -1.69282229, -1.60354025],
       [-1.35929125,  0.39912419, -0.5892535 ,  0.0361138 ,  0.21667773]])

In [130]:
from numpy.random import seed

In [156]:
for x in range(1, 11):
  seed(x)
  print(normal(size=(3, 5)))

[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]
 [-2.3015387   1.74481176 -0.7612069   0.3190391  -0.24937038]
 [ 1.46210794 -2.06014071 -0.3224172  -0.38405435  1.13376944]]
[[-0.41675785 -0.05626683 -2.1361961   1.64027081 -1.79343559]
 [-0.84174737  0.50288142 -1.24528809 -1.05795222 -0.90900761]
 [ 0.55145404  2.29220801  0.04153939 -1.11792545  0.53905832]]
[[ 1.78862847  0.43650985  0.09649747 -1.8634927  -0.2773882 ]
 [-0.35475898 -0.08274148 -0.62700068 -0.04381817 -0.47721803]
 [-1.31386475  0.88462238  0.88131804  1.70957306  0.05003364]]
[[ 0.05056171  0.49995133 -0.99590893  0.69359851 -0.41830152]
 [-1.58457724 -0.64770677  0.59857517  0.33225003 -1.14747663]
 [ 0.61866969 -0.08798693  0.4250724   0.33225315 -1.15681626]]
[[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
 [ 1.58248112 -0.9092324  -0.59163666  0.18760323 -0.32986996]
 [-1.19276461 -0.20487651 -0.35882895  0.6034716  -1.66478853]]
[[-0.31178367  0.72900392  0.21782079 -0.8990918  